# compose.yaml
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: game-api
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    networks:
      - game-network
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: development
    container_name: game-admin
    volumes:
      - ./admin:/app
      - admin_node_modules:/app/node_modules # 重要: node_modulesはコンテナ内に保持
    ports:
      - "5173:5173"
    networks:
    - game-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: game-nginx
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
    # apiコンテナが起動してからnginxコンテナを起動する
    depends_on:
      - api
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  admin_node_modules:
